---
title: "rtest1b"
date: October 31st, 2022
output:
  html_document:
    number_sections: true
vignette: >
  %\VignetteIndexEntry{rtest1b}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

## Problem Formulations

# Overview
The main task of the package `dsdp` is to estimate probability density
functions from a data set using a maximum likelihood method.
The models of density functions in use are familiar Gaussian 
or exponential distributions with polynomial correction terms.
We call Gaussian distribution with a polynomial **Gaussian-based model** and
an exponential distribution with a polynomial **Exponential-based model**,
respectively.
`dsdp` seeks parameters of Gaussian or exponential distributions 
together with degrees of polynomials using a grid search, and coefficients of
polynomials using a variant of semidefinite programming(SDP) problems.
Detailed discussions of SDP problem formulations and this type of SDP problems are
found in other vignettes.

The outline of estimation procedure is as follows.

1. Create Gaussian-based or Exponential-based model from a data set.
2. Explore a data set by checking the statistics and the histogram
3. Provide a set of parameters of Gaussian or exponential distributions
and degrees of polynomials.
4. Estimate the coefficients of the polynomials for a set of parameters and
then check the results by comparing Akaike Information Criterion(AIC) and
plotting density functions.
5. Refine the parameters and repeat 3-4 until a sufficient estimate is
obtained.

We will see each process step by step in the next section.
Before we move on, please install and import the package if you haven't yet.
Installation is done by
```{r eval=FALSE}
## Install from CRAN
install.packages('dsdp')
```
